# Generated by Django 5.1 on 2024-11-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='houseno',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='roadno',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
