# Generated by Django 5.1 on 2024-11-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_customer_houseno_customer_roadno'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='item',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
