# Generated by Django 5.1 on 2024-11-18 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_customer_item_customer_price_customer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='price',
        ),
    ]
