# Generated by Django 5.1 on 2024-11-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_customer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
