# Generated by Django 5.1 on 2024-11-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_customer_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
