# Generated by Django 5.1 on 2024-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_customer_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='lname',
        ),
        migrations.AlterField(
            model_name='customer',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
