# Generated by Django 5.1 on 2024-11-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
