# Generated by Django 5.1 on 2024-11-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='totalprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
