# Generated by Django 5.2 on 2025-07-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_customer_totalprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('action', models.CharField(max_length=255)),
            ],
        ),
    ]
