# Generated by Django 5.2 on 2025-07-09 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_remove_navigationlog_username_navigationlog_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NavigationLog',
        ),
    ]
