# Generated by Django 5.2 on 2025-07-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_navigationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigationlog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
