# Generated by Django 5.2.4 on 2025-12-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationlog',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
